site_name: Algo foundations
theme:
  name: material #readthedocs #mkdocs

nav:
  - Home: index.md
  - Resources: resources.md
  - Foundations:
    - Why Algorithms: foundations/why_algorithms.md
  # - Asymptotics: asymptotics.md
  # - Sorting: sorting.md
  # - Graphs: graphs.md
